"""sync transit api schema
  for v0.3.0

Revision ID: 664ae0905bb7
Revises: 9624f3823ec4
Create Date: 2026-02-07 12:01:37.022380

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664ae0905bb7'
down_revision: Union[str, Sequence[str], None] = '9624f3823ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('actor_admin_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('actor_key', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('resource_key', sa.String(length=128), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('http_method', sa.String(length=16), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('x_forwarded_for', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('succeeded', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['actor_admin_id'], ['admins.id'], name=op.f('fk_user_activity_events_actor_admin_id_admins'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_user_activity_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_activity_events'))
    )
    with op.batch_alter_table('user_activity_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_activity_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_events_actor_admin_id'), ['actor_admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_events_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_events_client_ip'), ['client_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_events_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_events_resource_id'), ['resource_id'], unique=False)

    op.create_table('bingo_period_rewards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('reward_nft_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['bingo_periods.id'], name=op.f('fk_bingo_period_rewards_period_id_bingo_periods'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reward_nft_id'], ['nfts.id'], name=op.f('fk_bingo_period_rewards_reward_nft_id_nfts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bingo_period_rewards')),
    sa.UniqueConstraint('period_id', name='uq_bingo_period_rewards_period')
    )
    with op.batch_alter_table('bingo_period_rewards', schema=None) as batch_op:
        batch_op.create_index('ix_bingo_period_rewards_enabled', ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_bingo_period_rewards_period_id'), ['period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bingo_period_rewards_reward_nft_id'), ['reward_nft_id'], unique=False)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('app_banners', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('bingo_card_issue_tasks', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)
        batch_op.alter_column('center_nft_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)
        batch_op.alter_column('ownership_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_bingo_card_issue_tasks_ownership_id'), type_='unique')
        batch_op.create_unique_constraint('bingo_card_issue_tasks_ownership_id_key', ['ownership_id'])

    with op.batch_alter_table('bingo_cards', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)
        batch_op.alter_column('bingo_reward_claimed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(false)'),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_bingo_card_user_month'), type_='unique')

    with op.batch_alter_table('bingo_cells', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('bingo_card_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)
        batch_op.alter_column('target_template_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)
        batch_op.alter_column('nft_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=True)
        batch_op.alter_column('matched_ownership_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=True)

    with op.batch_alter_table('coupon_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_nft_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True))
        batch_op.add_column(sa.Column('redeem_request_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('redeem_client_ip', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('redeem_x_forwarded_for', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('redeem_user_agent', sa.Text(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('template_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)
        batch_op.alter_column('nft_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=True)
        batch_op.alter_column('ownership_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_coupon_instances_coupon_code'), type_='unique')
        batch_op.create_unique_constraint('coupon_instances_coupon_code_key', ['coupon_code'])
        batch_op.create_index(batch_op.f('ix_coupon_instances_display_nft_id'), ['display_nft_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_coupon_instances_display_nft_id_nfts'), 'nfts', ['display_nft_id'], ['id'], ondelete='SET NULL')

    # Backfill display_nft_id to preserve legacy behavior.
    op.execute(
        sa.text(
            """
            UPDATE coupon_instances
            SET display_nft_id = nft_id
            WHERE display_nft_id IS NULL
              AND nft_id IS NOT NULL
            """
        )
    )

    # Initial reward coupons: if template has active bindings to other NFTs,
    # pick a deterministic display target (MIN binding NFT id != source NFT).
    op.execute(
        sa.text(
            """
            UPDATE coupon_instances
            SET display_nft_id = (
                SELECT MIN(b.nft_id)
                FROM nft_coupon_bindings b
                WHERE b.template_id = coupon_instances.template_id
                  AND b.active = true
                  AND b.nft_id IS NOT NULL
                  AND b.nft_id != coupon_instances.nft_id
            )
            WHERE coupon_instances.template_id IS NOT NULL
              AND coupon_instances.nft_id IS NOT NULL
              AND coupon_instances.nft_id IN (
                  SELECT n.id
                  FROM nfts n
                  WHERE n.nft_type = 'initial_reward'
              )
              AND EXISTS (
                  SELECT 1
                  FROM nft_coupon_bindings b2
                  WHERE b2.template_id = coupon_instances.template_id
                    AND b2.active = true
                    AND b2.nft_id IS NOT NULL
                    AND b2.nft_id != coupon_instances.nft_id
              )
            """
        )
    )

    with op.batch_alter_table('coupon_player_store_inventories', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('store_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)
        batch_op.alter_column('player_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)
        batch_op.alter_column('issued_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
        batch_op.alter_column('redeemed_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(true)'),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)

    with op.batch_alter_table('coupon_players', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('template_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)

    with op.batch_alter_table('coupon_stores', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('nft_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)
        batch_op.alter_column('store_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('coupon_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_per_user', sa.Integer(), server_default=sa.text('1'), nullable=True))
        batch_op.add_column(sa.Column('eligible_for_cross_promo', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
        batch_op.add_column(sa.Column('default_display_nft_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_constraint(batch_op.f('uq_coupon_templates_prefix'), type_='unique')
        batch_op.create_unique_constraint('coupon_templates_prefix_key', ['prefix'])
        batch_op.create_index(batch_op.f('ix_coupon_templates_default_display_nft_id'), ['default_display_nft_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_coupon_templates_default_display_nft_id_nfts'), 'nfts', ['default_display_nft_id'], ['id'], ondelete='SET NULL')

    # Ensure existing rows have explicit max_per_user defaults.
    op.execute(sa.text("UPDATE coupon_templates SET max_per_user = 1 WHERE max_per_user IS NULL"))

    # Keep unlimited issuance for templates bound to active bingo/bingo_reward NFTs.
    op.execute(
        sa.text(
            """
            UPDATE coupon_templates
            SET max_per_user = NULL
            WHERE id IN (
                SELECT DISTINCT b.template_id
                FROM nft_coupon_bindings b
                JOIN nfts n ON n.id = b.nft_id
                WHERE b.active = true
                  AND n.status = 'active'
                  AND n.nft_type IN ('bingo', 'bingo_reward')
            )
            """
        )
    )

    # Cross-promo initial policy.
    op.execute(sa.text("UPDATE coupon_templates SET eligible_for_cross_promo = false"))
    op.execute(
        sa.text(
            """
            UPDATE coupon_templates
            SET eligible_for_cross_promo = true
            WHERE id BETWEEN 76 AND 95
            """
        )
    )

    with op.batch_alter_table('external_accounts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('nft_claim_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bingo_line_completed', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
        batch_op.add_column(sa.Column('request_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('request_client_ip', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('request_x_forwarded_for', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('request_user_agent', sa.Text(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)
        batch_op.alter_column('nft_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)
        batch_op.alter_column('ownership_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=True)

    with op.batch_alter_table('nft_conditions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('nft_coupon_bindings', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('nft_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)
        batch_op.alter_column('template_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)

    with op.batch_alter_table('nft_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('default_condition_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=True)
        batch_op.alter_column('created_by_admin_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_nft_templates_prefix'), type_='unique')
        batch_op.create_unique_constraint('nft_templates_prefix_key', ['prefix'])

    op.execute(sa.text("UPDATE nft_templates SET is_public = true WHERE status = 'active'"))

    with op.batch_alter_table('nfts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bingo_period_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bingo_is_center', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
        batch_op.add_column(sa.Column('bingo_force_include', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
        batch_op.add_column(sa.Column('bingo_random_candidate', sa.Boolean(), server_default=sa.text('(true)'), nullable=False))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('template_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=True)
        batch_op.alter_column('condition_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=True)
        batch_op.alter_column('created_by_admin_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_nfts_prefix'), type_='unique')
        batch_op.create_index(batch_op.f('ix_nfts_bingo_period_id'), ['bingo_period_id'], unique=False)
        batch_op.create_unique_constraint('nfts_prefix_key', ['prefix'])
        batch_op.create_foreign_key(batch_op.f('fk_nfts_bingo_period_id_bingo_periods'), 'bingo_periods', ['bingo_period_id'], ['id'], ondelete='SET NULL')

    op.execute(sa.text("UPDATE nfts SET bingo_random_candidate = false WHERE id = 65"))
    op.execute(sa.text("UPDATE nfts SET is_public = true WHERE status = 'active'"))

    with op.batch_alter_table('pre_generated_bingo_cards', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('center_nft_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)

    with op.batch_alter_table('pre_minted_users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_constraint(batch_op.f('uq_pre_minted_users_on_chain_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_pre_minted_users_paymail'), type_='unique')
        batch_op.create_unique_constraint('pre_minted_users_on_chain_id_key', ['on_chain_id'])
        batch_op.create_unique_constraint('pre_minted_users_paymail_key', ['paymail'])

    with op.batch_alter_table('prize_draw_results', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)
        batch_op.alter_column('nft_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)
        batch_op.alter_column('ownership_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=True)

    with op.batch_alter_table('prize_draw_types', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_prize_draw_types_internal_name'), type_='unique')
        batch_op.create_unique_constraint('prize_draw_types_internal_name_key', ['internal_name'])

    with op.batch_alter_table('raffle_entries', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)
        batch_op.alter_column('bingo_card_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=True)
        batch_op.alter_column('ownership_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=True)

    with op.batch_alter_table('raffle_events', schema=None) as batch_op:
        batch_op.alter_column('scheduled_by_admin_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=True)
        batch_op.alter_column('winner_user_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=True)

    with op.batch_alter_table('user_nft_ownership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bingo_period_id', sa.Integer(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)
        batch_op.alter_column('nft_id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_user_nft_ownership_bingo_period_id'), ['bingo_period_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_user_nft_ownership_bingo_period_id_bingo_periods'), 'bingo_periods', ['bingo_period_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('initial_reward_claimed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(false)'),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_users_paymail'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_unique_constraint('users_paymail_key', ['paymail'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_paymail_key', type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_users_paymail'), ['paymail'])
        batch_op.alter_column('initial_reward_claimed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('user_nft_ownership', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_nft_ownership_bingo_period_id_bingo_periods'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_nft_ownership_bingo_period_id'))
        batch_op.alter_column('nft_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('bingo_period_id')

    with op.batch_alter_table('raffle_events', schema=None) as batch_op:
        batch_op.alter_column('winner_user_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('scheduled_by_admin_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=True)

    with op.batch_alter_table('raffle_entries', schema=None) as batch_op:
        batch_op.alter_column('ownership_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('bingo_card_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('prize_draw_types', schema=None) as batch_op:
        batch_op.drop_constraint('prize_draw_types_internal_name_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_prize_draw_types_internal_name'), ['internal_name'])

    with op.batch_alter_table('prize_draw_results', schema=None) as batch_op:
        batch_op.alter_column('ownership_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('nft_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('pre_minted_users', schema=None) as batch_op:
        batch_op.drop_constraint('pre_minted_users_paymail_key', type_='unique')
        batch_op.drop_constraint('pre_minted_users_on_chain_id_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_pre_minted_users_paymail'), ['paymail'])
        batch_op.create_unique_constraint(batch_op.f('uq_pre_minted_users_on_chain_id'), ['on_chain_id'])
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('pre_generated_bingo_cards', schema=None) as batch_op:
        batch_op.alter_column('center_nft_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('nfts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_nfts_bingo_period_id_bingo_periods'), type_='foreignkey')
        batch_op.drop_constraint('nfts_prefix_key', type_='unique')
        batch_op.drop_index(batch_op.f('ix_nfts_bingo_period_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_nfts_prefix'), ['prefix'])
        batch_op.alter_column('created_by_admin_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('condition_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('template_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('is_public')
        batch_op.drop_column('bingo_random_candidate')
        batch_op.drop_column('bingo_force_include')
        batch_op.drop_column('bingo_is_center')
        batch_op.drop_column('bingo_period_id')

    with op.batch_alter_table('nft_templates', schema=None) as batch_op:
        batch_op.drop_constraint('nft_templates_prefix_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_nft_templates_prefix'), ['prefix'])
        batch_op.alter_column('created_by_admin_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('default_condition_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('is_public')

    with op.batch_alter_table('nft_coupon_bindings', schema=None) as batch_op:
        batch_op.alter_column('template_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('nft_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('nft_conditions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('nft_claim_requests', schema=None) as batch_op:
        batch_op.alter_column('ownership_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('nft_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('request_user_agent')
        batch_op.drop_column('request_x_forwarded_for')
        batch_op.drop_column('request_client_ip')
        batch_op.drop_column('request_id')
        batch_op.drop_column('bingo_line_completed')

    with op.batch_alter_table('external_accounts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('coupon_templates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_coupon_templates_default_display_nft_id_nfts'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_coupon_templates_default_display_nft_id'))
        batch_op.drop_constraint('coupon_templates_prefix_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_coupon_templates_prefix'), ['prefix'])
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('default_display_nft_id')
        batch_op.drop_column('eligible_for_cross_promo')
        batch_op.drop_column('max_per_user')

    with op.batch_alter_table('coupon_stores', schema=None) as batch_op:
        batch_op.alter_column('store_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('nft_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('coupon_players', schema=None) as batch_op:
        batch_op.alter_column('template_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('coupon_player_store_inventories', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('redeemed_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('issued_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('player_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('store_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('coupon_instances', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_coupon_instances_display_nft_id_nfts'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_coupon_instances_display_nft_id'))
        batch_op.drop_constraint('coupon_instances_coupon_code_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_coupon_instances_coupon_code'), ['coupon_code'])
        batch_op.alter_column('ownership_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('nft_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('template_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('redeem_user_agent')
        batch_op.drop_column('redeem_x_forwarded_for')
        batch_op.drop_column('redeem_client_ip')
        batch_op.drop_column('redeem_request_id')
        batch_op.drop_column('display_nft_id')

    with op.batch_alter_table('bingo_cells', schema=None) as batch_op:
        batch_op.alter_column('matched_ownership_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('nft_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('target_template_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('bingo_card_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('bingo_cards', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_bingo_card_user_month'), ['user_id', 'issuance_month'])
        batch_op.alter_column('bingo_reward_claimed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('bingo_card_issue_tasks', schema=None) as batch_op:
        batch_op.drop_constraint('bingo_card_issue_tasks_ownership_id_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_bingo_card_issue_tasks_ownership_id'), ['ownership_id'])
        batch_op.alter_column('ownership_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('center_nft_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('app_banners', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('bingo_period_rewards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bingo_period_rewards_reward_nft_id'))
        batch_op.drop_index(batch_op.f('ix_bingo_period_rewards_period_id'))
        batch_op.drop_index('ix_bingo_period_rewards_enabled')

    op.drop_table('bingo_period_rewards')
    with op.batch_alter_table('user_activity_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_activity_events_resource_id'))
        batch_op.drop_index(batch_op.f('ix_user_activity_events_request_id'))
        batch_op.drop_index(batch_op.f('ix_user_activity_events_id'))
        batch_op.drop_index(batch_op.f('ix_user_activity_events_client_ip'))
        batch_op.drop_index(batch_op.f('ix_user_activity_events_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_activity_events_actor_admin_id'))
        batch_op.drop_index(batch_op.f('ix_user_activity_events_action'))

    op.drop_table('user_activity_events')
    # ### end Alembic commands ###
