"""baseline api schema

Revision ID: 9624f3823ec4
Revises: 
Create Date: 2026-01-12 01:39:30.464635

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9624f3823ec4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins'))
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_admins_id'), ['id'], unique=False)

    op.create_table('app_banners',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link_url', sa.String(length=512), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('target_uids', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_banners'))
    )
    with op.batch_alter_table('app_banners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_banners_id'), ['id'], unique=False)

    op.create_table('bingo_periods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bingo_periods'))
    )
    op.create_table('coupon_templates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prefix', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('next_serial', sa.Integer(), nullable=False),
    sa.Column('max_supply', sa.Integer(), nullable=True),
    sa.Column('max_redeem', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expiry_days', sa.Integer(), nullable=True),
    sa.Column('store_name', sa.String(length=255), nullable=True),
    sa.Column('short_description', sa.String(length=255), nullable=True),
    sa.Column('available_stores', sa.Text(), nullable=True),
    sa.Column('usage_restrictions', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('fixed_expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupon_templates')),
    sa.UniqueConstraint('prefix', name=op.f('uq_coupon_templates_prefix'))
    )
    with op.batch_alter_table('coupon_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupon_templates_id'), ['id'], unique=False)

    op.create_table('nft_conditions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('radius', sa.Float(), nullable=True),
    sa.Column('required_nft_id', sa.BigInteger(), nullable=True),
    sa.Column('prohibited_nft_id', sa.BigInteger(), nullable=True),
    sa.Column('other_conditions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nft_conditions'))
    )
    with op.batch_alter_table('nft_conditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nft_conditions_id'), ['id'], unique=False)

    op.create_table('pre_minted_users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('on_chain_id', sa.String(length=255), nullable=False),
    sa.Column('paymail', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pre_minted_users')),
    sa.UniqueConstraint('on_chain_id', name=op.f('uq_pre_minted_users_on_chain_id')),
    sa.UniqueConstraint('paymail', name=op.f('uq_pre_minted_users_paymail'))
    )
    with op.batch_alter_table('pre_minted_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pre_minted_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pre_minted_users_status'), ['status'], unique=False)

    op.create_table('prize_draw_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('draw_type_id', sa.Integer(), nullable=False),
    sa.Column('winning_number_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('nft_id', sa.BigInteger(), nullable=False),
    sa.Column('ownership_id', sa.BigInteger(), nullable=True),
    sa.Column('draw_number', sa.String(length=255), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('draw_top_digits', sa.String(length=10), nullable=True),
    sa.Column('winning_top_digits', sa.String(length=10), nullable=True),
    sa.Column('threshold_used', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prize_draw_results')),
    sa.UniqueConstraint('nft_id', 'draw_type_id', name='uq_prize_draw_result_unique')
    )
    with op.batch_alter_table('prize_draw_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prize_draw_results_draw_type_id'), ['draw_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prize_draw_results_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prize_draw_results_nft_id'), ['nft_id'], unique=False)
        batch_op.create_index('ix_prize_draw_results_outcome', ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_prize_draw_results_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prize_draw_results_winning_number_id'), ['winning_number_id'], unique=False)

    op.create_table('prize_draw_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('internal_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('algorithm_key', sa.String(length=100), nullable=False),
    sa.Column('default_threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prize_draw_types')),
    sa.UniqueConstraint('internal_name', name=op.f('uq_prize_draw_types_internal_name'))
    )
    op.create_table('raffle_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draw_type_id', sa.Integer(), nullable=False),
    sa.Column('winning_number_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_by_admin_id', sa.BigInteger(), nullable=True),
    sa.Column('winner_user_id', sa.BigInteger(), nullable=True),
    sa.Column('winner_result_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raffle_events'))
    )
    with op.batch_alter_table('raffle_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raffle_events_draw_type_id'), ['draw_type_id'], unique=False)

    op.create_table('system_configurations',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_configurations'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('in_app_id', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('password_provided', sa.Boolean(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('paymail', sa.String(length=255), nullable=True),
    sa.Column('on_chain_id', sa.String(length=255), nullable=True),
    sa.Column('fcm_token', sa.String(length=255), nullable=True),
    sa.Column('initial_reward_claimed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('paymail', name=op.f('uq_users_paymail'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_in_app_id'), ['in_app_id'], unique=True)

    op.create_table('bingo_cards',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issuance_month', sa.String(length=7), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('bingo_reward_claimed', sa.Boolean(), nullable=False),
    sa.CheckConstraint("state IN ('active','completed','expired')", name=op.f('ck_bingo_cards_bingo_card_state_enum')),
    sa.ForeignKeyConstraint(['period_id'], ['bingo_periods.id'], name=op.f('fk_bingo_cards_period_id_bingo_periods')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bingo_cards_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bingo_cards')),
    sa.UniqueConstraint('user_id', 'issuance_month', name='uq_bingo_card_user_month')
    )
    with op.batch_alter_table('bingo_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bingo_cards_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bingo_cards_user_id'), ['user_id'], unique=False)

    op.create_table('coupon_players',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=False),
    sa.Column('name_ja', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('positions', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('template_id', sa.BigInteger(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['coupon_templates.id'], name=op.f('fk_coupon_players_template_id_coupon_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupon_players')),
    sa.UniqueConstraint('jersey_number', name='uq_coupon_players_jersey')
    )
    with op.batch_alter_table('coupon_players', schema=None) as batch_op:
        batch_op.create_index('ix_coupon_players_active', ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_players_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_players_jersey_number'), ['jersey_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_players_template_id'), ['template_id'], unique=True)

    op.create_table('external_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_external_accounts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_accounts'))
    )
    with op.batch_alter_table('external_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_accounts_id'), ['id'], unique=False)

    op.create_table('nft_templates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prefix', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('qr_image_url', sa.String(length=255), nullable=True),
    sa.Column('max_supply', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('default_condition_id', sa.BigInteger(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('radius', sa.Float(), nullable=True),
    sa.Column('required_nft_id', sa.BigInteger(), nullable=True),
    sa.Column('prohibited_nft_id', sa.BigInteger(), nullable=True),
    sa.Column('other_conditions', sa.Text(), nullable=True),
    sa.Column('triggers_bingo_card', sa.Boolean(), nullable=False),
    sa.Column('created_by_admin_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], name=op.f('fk_nft_templates_created_by_admin_id_admins')),
    sa.ForeignKeyConstraint(['default_condition_id'], ['nft_conditions.id'], name=op.f('fk_nft_templates_default_condition_id_nft_conditions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nft_templates')),
    sa.UniqueConstraint('prefix', name=op.f('uq_nft_templates_prefix'))
    )
    with op.batch_alter_table('nft_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nft_templates_id'), ['id'], unique=False)

    op.create_table('prize_draw_winning_numbers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draw_type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draw_type_id'], ['prize_draw_types.id'], name=op.f('fk_prize_draw_winning_numbers_draw_type_id_prize_draw_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prize_draw_winning_numbers'))
    )
    with op.batch_alter_table('prize_draw_winning_numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prize_draw_winning_numbers_draw_type_id'), ['draw_type_id'], unique=False)

    op.create_table('nfts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=True),
    sa.Column('prefix', sa.String(length=100), nullable=False),
    sa.Column('shared_key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('nft_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('promotional_text', sa.Text(), nullable=True),
    sa.Column('store_url', sa.String(length=512), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('local_image_path', sa.String(length=255), nullable=True),
    sa.Column('qr_image_url', sa.String(length=255), nullable=True),
    sa.Column('condition_id', sa.BigInteger(), nullable=True),
    sa.Column('max_supply', sa.Integer(), nullable=True),
    sa.Column('minted_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('triggers_bingo_card', sa.Boolean(), nullable=False),
    sa.Column('distributes_coupons', sa.Boolean(), nullable=False),
    sa.Column('is_dummy', sa.Boolean(), nullable=False),
    sa.Column('can_be_center', sa.Boolean(), nullable=False),
    sa.Column('store_name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_by_admin_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['nft_conditions.id'], name=op.f('fk_nfts_condition_id_nft_conditions')),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], name=op.f('fk_nfts_created_by_admin_id_admins')),
    sa.ForeignKeyConstraint(['template_id'], ['nft_templates.id'], name=op.f('fk_nfts_template_id_nft_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nfts')),
    sa.UniqueConstraint('prefix', name=op.f('uq_nfts_prefix'))
    )
    with op.batch_alter_table('nfts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfts_template_id'), ['template_id'], unique=False)

    op.create_table('coupon_stores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nft_id', sa.BigInteger(), nullable=False),
    sa.Column('usage_restrictions', sa.Text(), nullable=True),
    sa.Column('available_stores', sa.Text(), nullable=True),
    sa.Column('store_name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], name=op.f('fk_coupon_stores_nft_id_nfts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupon_stores')),
    sa.UniqueConstraint('name', name='uq_coupon_stores_name')
    )
    with op.batch_alter_table('coupon_stores', schema=None) as batch_op:
        batch_op.create_index('ix_coupon_stores_active', ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_stores_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_stores_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_stores_nft_id'), ['nft_id'], unique=True)

    op.create_table('nft_coupon_bindings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nft_id', sa.BigInteger(), nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity_per_claim', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], name=op.f('fk_nft_coupon_bindings_nft_id_nfts')),
    sa.ForeignKeyConstraint(['template_id'], ['coupon_templates.id'], name=op.f('fk_nft_coupon_bindings_template_id_coupon_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nft_coupon_bindings'))
    )
    with op.batch_alter_table('nft_coupon_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nft_coupon_bindings_id'), ['id'], unique=False)

    op.create_table('pre_generated_bingo_cards',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('center_nft_id', sa.BigInteger(), nullable=False),
    sa.Column('cell_nft_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['center_nft_id'], ['nfts.id'], name=op.f('fk_pre_generated_bingo_cards_center_nft_id_nfts')),
    sa.ForeignKeyConstraint(['period_id'], ['bingo_periods.id'], name=op.f('fk_pre_generated_bingo_cards_period_id_bingo_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pre_generated_bingo_cards'))
    )
    with op.batch_alter_table('pre_generated_bingo_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pre_generated_bingo_cards_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pre_generated_bingo_cards_status'), ['status'], unique=False)

    op.create_table('user_nft_ownership',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('nft_id', sa.BigInteger(), nullable=False),
    sa.Column('serial_number', sa.Integer(), nullable=False),
    sa.Column('unique_nft_id', sa.String(length=255), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('blockchain_nft_id', sa.BigInteger(), nullable=True),
    sa.Column('nft_origin', sa.String(length=255), nullable=True),
    sa.Column('current_nft_location', sa.String(length=255), nullable=True),
    sa.Column('blockchain_name', sa.String(length=100), nullable=True),
    sa.Column('sub_type', sa.String(length=50), nullable=True),
    sa.Column('blockchain_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blockchain_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('contract_address', sa.String(length=255), nullable=True),
    sa.Column('token_id', sa.String(length=255), nullable=True),
    sa.Column('other_meta', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], name=op.f('fk_user_nft_ownership_nft_id_nfts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_nft_ownership_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_nft_ownership')),
    sa.UniqueConstraint('user_id', 'nft_id', name='uq_user_nft_once')
    )
    with op.batch_alter_table('user_nft_ownership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_nft_ownership_id'), ['id'], unique=False)

    op.create_table('bingo_card_issue_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('center_nft_id', sa.BigInteger(), nullable=False),
    sa.Column('ownership_id', sa.BigInteger(), nullable=False),
    sa.Column('unique_nft_ref', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending','processing','succeeded','failed','blocked')", name=op.f('ck_bingo_card_issue_tasks_bingo_issue_status_enum')),
    sa.ForeignKeyConstraint(['center_nft_id'], ['nfts.id'], name=op.f('fk_bingo_card_issue_tasks_center_nft_id_nfts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ownership_id'], ['user_nft_ownership.id'], name=op.f('fk_bingo_card_issue_tasks_ownership_id_user_nft_ownership'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bingo_card_issue_tasks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bingo_card_issue_tasks')),
    sa.UniqueConstraint('ownership_id', name=op.f('uq_bingo_card_issue_tasks_ownership_id'))
    )
    with op.batch_alter_table('bingo_card_issue_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bingo_card_issue_tasks_center_nft_id'), ['center_nft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bingo_card_issue_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bingo_card_issue_tasks_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_bingo_issue_status_run', ['status', 'next_run_at'], unique=False)

    op.create_table('bingo_cells',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bingo_card_id', sa.BigInteger(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('target_template_id', sa.BigInteger(), nullable=False),
    sa.Column('nft_id', sa.BigInteger(), nullable=True),
    sa.Column('matched_ownership_id', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('locked','unlocked')", name=op.f('ck_bingo_cells_bingo_cell_state_enum')),
    sa.CheckConstraint('idx >= 0 AND idx <= 8', name=op.f('ck_bingo_cells_bingo_cell_idx_range')),
    sa.ForeignKeyConstraint(['bingo_card_id'], ['bingo_cards.id'], name=op.f('fk_bingo_cells_bingo_card_id_bingo_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_ownership_id'], ['user_nft_ownership.id'], name=op.f('fk_bingo_cells_matched_ownership_id_user_nft_ownership'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], name=op.f('fk_bingo_cells_nft_id_nfts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_template_id'], ['nfts.id'], name=op.f('fk_bingo_cells_target_template_id_nfts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bingo_cells')),
    sa.UniqueConstraint('bingo_card_id', 'idx', name='uq_bingo_card_idx')
    )
    with op.batch_alter_table('bingo_cells', schema=None) as batch_op:
        batch_op.create_index('ix_bingo_cells_card', ['bingo_card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bingo_cells_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bingo_cells_nft_id'), ['nft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bingo_cells_target_template_id'), ['target_template_id'], unique=False)

    op.create_table('coupon_instances',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=False),
    sa.Column('nft_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('ownership_id', sa.BigInteger(), nullable=True),
    sa.Column('serial_number', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sa.String(length=128), nullable=False),
    sa.Column('usage_latitude', sa.Float(), nullable=True),
    sa.Column('usage_longitude', sa.Float(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redeemed', sa.Boolean(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('store_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=255), nullable=True),
    sa.Column('available_stores', sa.Text(), nullable=True),
    sa.Column('usage_restrictions', sa.Text(), nullable=True),
    sa.Column('player_usage_restrictions', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], name=op.f('fk_coupon_instances_nft_id_nfts')),
    sa.ForeignKeyConstraint(['ownership_id'], ['user_nft_ownership.id'], name=op.f('fk_coupon_instances_ownership_id_user_nft_ownership')),
    sa.ForeignKeyConstraint(['template_id'], ['coupon_templates.id'], name=op.f('fk_coupon_instances_template_id_coupon_templates')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_coupon_instances_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupon_instances')),
    sa.UniqueConstraint('coupon_code', name=op.f('uq_coupon_instances_coupon_code'))
    )
    with op.batch_alter_table('coupon_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupon_instances_id'), ['id'], unique=False)

    op.create_table('coupon_player_store_inventories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('max_supply', sa.Integer(), nullable=True),
    sa.Column('issued_count', sa.Integer(), nullable=False),
    sa.Column('max_redeem', sa.Integer(), nullable=True),
    sa.Column('redeemed_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('issued_count >= 0', name=op.f('ck_coupon_player_store_inventories_ck_cpsi_issued_count_nonneg')),
    sa.CheckConstraint('max_redeem IS NULL OR max_redeem >= 0', name=op.f('ck_coupon_player_store_inventories_ck_cpsi_max_redeem_nonneg')),
    sa.CheckConstraint('max_supply IS NULL OR max_redeem IS NULL OR max_redeem <= max_supply', name=op.f('ck_coupon_player_store_inventories_ck_cpsi_max_redeem_le_max_supply')),
    sa.CheckConstraint('max_supply IS NULL OR max_supply >= 0', name=op.f('ck_coupon_player_store_inventories_ck_cpsi_max_supply_nonneg')),
    sa.CheckConstraint('redeemed_count >= 0', name=op.f('ck_coupon_player_store_inventories_ck_cpsi_redeemed_count_nonneg')),
    sa.ForeignKeyConstraint(['player_id'], ['coupon_players.id'], name=op.f('fk_coupon_player_store_inventories_player_id_coupon_players'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['coupon_stores.id'], name=op.f('fk_coupon_player_store_inventories_store_id_coupon_stores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupon_player_store_inventories')),
    sa.UniqueConstraint('store_id', 'player_id', name='uq_coupon_player_store')
    )
    with op.batch_alter_table('coupon_player_store_inventories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupon_player_store_inventories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_player_store_inventories_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_player_store_inventories_store_id'), ['store_id'], unique=False)
        batch_op.create_index('ix_cpsi_active', ['active'], unique=False)

    op.create_table('nft_claim_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tmp_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('nft_id', sa.BigInteger(), nullable=False),
    sa.Column('prefix', sa.String(length=100), nullable=False),
    sa.Column('shared_key', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ownership_id', sa.BigInteger(), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('coupon_status', sa.String(length=20), nullable=False),
    sa.Column('coupon_attempts', sa.Integer(), nullable=False),
    sa.Column('coupon_next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coupon_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], name=op.f('fk_nft_claim_requests_nft_id_nfts')),
    sa.ForeignKeyConstraint(['ownership_id'], ['user_nft_ownership.id'], name=op.f('fk_nft_claim_requests_ownership_id_user_nft_ownership')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_nft_claim_requests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nft_claim_requests')),
    sa.UniqueConstraint('tmp_id', name='uq_nft_claim_tmp_id'),
    sa.UniqueConstraint('tmp_id', name=op.f('uq_nft_claim_requests_tmp_id')),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_nft_claim_idempotency')
    )
    with op.batch_alter_table('nft_claim_requests', schema=None) as batch_op:
        batch_op.create_index('ix_nft_claim_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nft_claim_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nft_claim_requests_nft_id'), ['nft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nft_claim_requests_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_nft_claim_user_status', ['user_id', 'status'], unique=False)

    op.create_table('raffle_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('bingo_card_id', sa.BigInteger(), nullable=True),
    sa.Column('ownership_id', sa.BigInteger(), nullable=True),
    sa.Column('raffle_event_id', sa.Integer(), nullable=True),
    sa.Column('line_signature', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bingo_card_id'], ['bingo_cards.id'], name=op.f('fk_raffle_entries_bingo_card_id_bingo_cards'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ownership_id'], ['user_nft_ownership.id'], name=op.f('fk_raffle_entries_ownership_id_user_nft_ownership'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raffle_event_id'], ['raffle_events.id'], name=op.f('fk_raffle_entries_raffle_event_id_raffle_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_raffle_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raffle_entries')),
    sa.UniqueConstraint('user_id', 'bingo_card_id', name='uq_raffle_entry_per_card')
    )
    with op.batch_alter_table('raffle_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raffle_entries_user_id'), ['user_id'], unique=False)

    # Add foreign keys after table creation to avoid ordering/cycle issues.
    with op.batch_alter_table('raffle_events', schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f('fk_raffle_events_draw_type_id_prize_draw_types'),
            'prize_draw_types',
            ['draw_type_id'],
            ['id'],
            ondelete='RESTRICT',
        )
        batch_op.create_foreign_key(
            batch_op.f('fk_raffle_events_winning_number_id_prize_draw_winning_numbers'),
            'prize_draw_winning_numbers',
            ['winning_number_id'],
            ['id'],
            ondelete='SET NULL',
        )
        batch_op.create_foreign_key(
            batch_op.f('fk_raffle_events_scheduled_by_admin_id_admins'),
            'admins',
            ['scheduled_by_admin_id'],
            ['id'],
            ondelete='SET NULL',
        )
        batch_op.create_foreign_key(
            batch_op.f('fk_raffle_events_winner_user_id_users'),
            'users',
            ['winner_user_id'],
            ['id'],
            ondelete='SET NULL',
        )
        batch_op.create_foreign_key(
            batch_op.f('fk_raffle_events_winner_result_id_prize_draw_results'),
            'prize_draw_results',
            ['winner_result_id'],
            ['id'],
            ondelete='SET NULL',
        )

    with op.batch_alter_table('prize_draw_results', schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f('fk_prize_draw_results_draw_type_id_prize_draw_types'),
            'prize_draw_types',
            ['draw_type_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            batch_op.f('fk_prize_draw_results_winning_number_id_prize_draw_winning_numbers'),
            'prize_draw_winning_numbers',
            ['winning_number_id'],
            ['id'],
            ondelete='SET NULL',
        )
        batch_op.create_foreign_key(
            batch_op.f('fk_prize_draw_results_user_id_users'),
            'users',
            ['user_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            batch_op.f('fk_prize_draw_results_nft_id_nfts'),
            'nfts',
            ['nft_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            batch_op.f('fk_prize_draw_results_ownership_id_user_nft_ownership'),
            'user_nft_ownership',
            ['ownership_id'],
            ['id'],
            ondelete='SET NULL',
        )
        batch_op.create_foreign_key(
            batch_op.f('fk_prize_draw_results_event_id_raffle_events'),
            'raffle_events',
            ['event_id'],
            ['id'],
            ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prize_draw_results', schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f('fk_prize_draw_results_event_id_raffle_events'),
            type_='foreignkey',
        )
        batch_op.drop_constraint(
            batch_op.f('fk_prize_draw_results_ownership_id_user_nft_ownership'),
            type_='foreignkey',
        )
        batch_op.drop_constraint(
            batch_op.f('fk_prize_draw_results_nft_id_nfts'),
            type_='foreignkey',
        )
        batch_op.drop_constraint(
            batch_op.f('fk_prize_draw_results_user_id_users'),
            type_='foreignkey',
        )
        batch_op.drop_constraint(
            batch_op.f('fk_prize_draw_results_winning_number_id_prize_draw_winning_numbers'),
            type_='foreignkey',
        )
        batch_op.drop_constraint(
            batch_op.f('fk_prize_draw_results_draw_type_id_prize_draw_types'),
            type_='foreignkey',
        )

    with op.batch_alter_table('raffle_events', schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f('fk_raffle_events_winner_result_id_prize_draw_results'),
            type_='foreignkey',
        )
        batch_op.drop_constraint(
            batch_op.f('fk_raffle_events_winner_user_id_users'),
            type_='foreignkey',
        )
        batch_op.drop_constraint(
            batch_op.f('fk_raffle_events_scheduled_by_admin_id_admins'),
            type_='foreignkey',
        )
        batch_op.drop_constraint(
            batch_op.f('fk_raffle_events_winning_number_id_prize_draw_winning_numbers'),
            type_='foreignkey',
        )
        batch_op.drop_constraint(
            batch_op.f('fk_raffle_events_draw_type_id_prize_draw_types'),
            type_='foreignkey',
        )

    with op.batch_alter_table('raffle_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raffle_entries_user_id'))

    op.drop_table('raffle_entries')
    with op.batch_alter_table('nft_claim_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_nft_claim_user_status')
        batch_op.drop_index(batch_op.f('ix_nft_claim_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_nft_claim_requests_nft_id'))
        batch_op.drop_index(batch_op.f('ix_nft_claim_requests_id'))
        batch_op.drop_index('ix_nft_claim_created')

    op.drop_table('nft_claim_requests')
    with op.batch_alter_table('coupon_player_store_inventories', schema=None) as batch_op:
        batch_op.drop_index('ix_cpsi_active')
        batch_op.drop_index(batch_op.f('ix_coupon_player_store_inventories_store_id'))
        batch_op.drop_index(batch_op.f('ix_coupon_player_store_inventories_player_id'))
        batch_op.drop_index(batch_op.f('ix_coupon_player_store_inventories_id'))

    op.drop_table('coupon_player_store_inventories')
    with op.batch_alter_table('coupon_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupon_instances_id'))

    op.drop_table('coupon_instances')
    with op.batch_alter_table('bingo_cells', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bingo_cells_target_template_id'))
        batch_op.drop_index(batch_op.f('ix_bingo_cells_nft_id'))
        batch_op.drop_index(batch_op.f('ix_bingo_cells_id'))
        batch_op.drop_index('ix_bingo_cells_card')

    op.drop_table('bingo_cells')
    with op.batch_alter_table('bingo_card_issue_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_bingo_issue_status_run')
        batch_op.drop_index(batch_op.f('ix_bingo_card_issue_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_bingo_card_issue_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_bingo_card_issue_tasks_center_nft_id'))

    op.drop_table('bingo_card_issue_tasks')
    with op.batch_alter_table('user_nft_ownership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_nft_ownership_id'))

    op.drop_table('user_nft_ownership')
    with op.batch_alter_table('pre_generated_bingo_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pre_generated_bingo_cards_status'))
        batch_op.drop_index(batch_op.f('ix_pre_generated_bingo_cards_id'))

    op.drop_table('pre_generated_bingo_cards')
    with op.batch_alter_table('nft_coupon_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nft_coupon_bindings_id'))

    op.drop_table('nft_coupon_bindings')
    with op.batch_alter_table('coupon_stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupon_stores_nft_id'))
        batch_op.drop_index(batch_op.f('ix_coupon_stores_name'))
        batch_op.drop_index(batch_op.f('ix_coupon_stores_id'))
        batch_op.drop_index('ix_coupon_stores_active')

    op.drop_table('coupon_stores')
    with op.batch_alter_table('nfts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfts_template_id'))
        batch_op.drop_index(batch_op.f('ix_nfts_id'))

    op.drop_table('nfts')
    with op.batch_alter_table('prize_draw_winning_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prize_draw_winning_numbers_draw_type_id'))

    op.drop_table('prize_draw_winning_numbers')
    with op.batch_alter_table('nft_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nft_templates_id'))

    op.drop_table('nft_templates')
    with op.batch_alter_table('external_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_accounts_id'))

    op.drop_table('external_accounts')
    with op.batch_alter_table('coupon_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupon_players_template_id'))
        batch_op.drop_index(batch_op.f('ix_coupon_players_jersey_number'))
        batch_op.drop_index(batch_op.f('ix_coupon_players_id'))
        batch_op.drop_index('ix_coupon_players_active')

    op.drop_table('coupon_players')
    with op.batch_alter_table('bingo_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bingo_cards_user_id'))
        batch_op.drop_index(batch_op.f('ix_bingo_cards_id'))

    op.drop_table('bingo_cards')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_in_app_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('system_configurations')
    with op.batch_alter_table('raffle_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raffle_events_draw_type_id'))

    op.drop_table('raffle_events')
    op.drop_table('prize_draw_types')
    with op.batch_alter_table('prize_draw_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prize_draw_results_winning_number_id'))
        batch_op.drop_index(batch_op.f('ix_prize_draw_results_user_id'))
        batch_op.drop_index('ix_prize_draw_results_outcome')
        batch_op.drop_index(batch_op.f('ix_prize_draw_results_nft_id'))
        batch_op.drop_index(batch_op.f('ix_prize_draw_results_event_id'))
        batch_op.drop_index(batch_op.f('ix_prize_draw_results_draw_type_id'))

    op.drop_table('prize_draw_results')
    with op.batch_alter_table('pre_minted_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pre_minted_users_status'))
        batch_op.drop_index(batch_op.f('ix_pre_minted_users_id'))

    op.drop_table('pre_minted_users')
    with op.batch_alter_table('nft_conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nft_conditions_id'))

    op.drop_table('nft_conditions')
    with op.batch_alter_table('coupon_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupon_templates_id'))

    op.drop_table('coupon_templates')
    op.drop_table('bingo_periods')
    with op.batch_alter_table('app_banners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_banners_id'))

    op.drop_table('app_banners')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_id'))
        batch_op.drop_index(batch_op.f('ix_admins_email'))

    op.drop_table('admins')
    # ### end Alembic commands ###
