"""initial schema

Revision ID: a287a719a914
Revises: 
Create Date: 2025-11-19 19:31:22.021765

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a287a719a914'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paymail', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
    sa.UniqueConstraint('paymail', name=op.f('uq_admins_paymail'))
    )
    op.create_table('coupon_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prefix', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('next_serial', sa.Integer(), nullable=False),
    sa.Column('max_supply', sa.Integer(), nullable=True),
    sa.Column('max_redeem', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expiry_days', sa.Integer(), nullable=True),
    sa.Column('store_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupon_templates')),
    sa.UniqueConstraint('prefix', name=op.f('uq_coupon_templates_prefix'))
    )
    with op.batch_alter_table('coupon_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupon_templates_id'), ['id'], unique=False)

    op.create_table('nft_conditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('internal_name', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_range', sa.Text(), nullable=True),
    sa.Column('required_nft_id', sa.Integer(), nullable=True),
    sa.Column('prohibited_nft_id', sa.Integer(), nullable=True),
    sa.Column('other_conditions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prohibited_nft_id'], ['nfts.id'], name=op.f('fk_nft_conditions_prohibited_nft_id_nfts'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['required_nft_id'], ['nfts.id'], name=op.f('fk_nft_conditions_required_nft_id_nfts'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nft_conditions'))
    )
    with op.batch_alter_table('nft_conditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nft_conditions_internal_name'), ['internal_name'], unique=True)

    op.create_table('prize_draw_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('internal_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('algorithm_key', sa.String(length=100), nullable=False),
    sa.Column('default_threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prize_draw_types')),
    sa.UniqueConstraint('internal_name', name=op.f('uq_prize_draw_types_internal_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('in_app_id', sa.String(length=64), nullable=False),
    sa.Column('paymail', sa.String(length=100), nullable=False),
    sa.Column('login_mail', sa.String(length=100), nullable=True),
    sa.Column('on_chain_id', sa.String(length=50), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('in_app_id', name=op.f('uq_users_in_app_id')),
    sa.UniqueConstraint('login_mail', name=op.f('uq_users_login_mail')),
    sa.UniqueConstraint('on_chain_id', name=op.f('uq_users_on_chain_id')),
    sa.UniqueConstraint('paymail', name=op.f('uq_users_paymail'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_admin_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('subject_table', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("actor_type IN ('system','admin','user')", name=op.f('ck_audit_logs_actor_type_enum')),
    sa.ForeignKeyConstraint(['actor_admin_id'], ['admins.id'], name=op.f('fk_audit_logs_actor_admin_id_admins'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('bingo_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.CheckConstraint("state IN ('active','completed','expired')", name=op.f('ck_bingo_cards_state_enum')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bingo_cards_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bingo_cards'))
    )
    with op.batch_alter_table('bingo_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bingo_cards_user_id'), ['user_id'], unique=False)

    op.create_table('nft_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prefix', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=False),
    sa.Column('default_condition_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('max_supply', sa.Integer(), nullable=True),
    sa.Column('minted_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('triggers_bingo_card', sa.Boolean(), nullable=False),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('active','inactive','archived')", name=op.f('ck_nft_templates_status_enum')),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], name=op.f('fk_nft_templates_created_by_admin_id_admins')),
    sa.ForeignKeyConstraint(['default_condition_id'], ['nft_conditions.id'], name=op.f('fk_nft_templates_default_condition_id_nft_conditions'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nft_templates')),
    sa.UniqueConstraint('category', 'subcategory', name='uq_category_subcategory')
    )
    with op.batch_alter_table('nft_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nft_templates_prefix'), ['prefix'], unique=True)

    op.create_table('prize_draw_winning_numbers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draw_type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['draw_type_id'], ['prize_draw_types.id'], name=op.f('fk_prize_draw_winning_numbers_draw_type_id_prize_draw_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prize_draw_winning_numbers'))
    )
    with op.batch_alter_table('prize_draw_winning_numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prize_draw_winning_numbers_draw_type_id'), ['draw_type_id'], unique=False)

    op.create_table('nfts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=100), nullable=True),
    sa.Column('shared_key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('id_on_chain', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=128), nullable=True),
    sa.Column('current_location', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('condition_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('active','inactive','archived')", name=op.f('ck_nfts_status_enum')),
    sa.ForeignKeyConstraint(['condition_id'], ['nft_conditions.id'], name=op.f('fk_nfts_condition_id_nft_conditions'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], name=op.f('fk_nfts_created_by_admin_id_admins')),
    sa.ForeignKeyConstraint(['template_id'], ['nft_templates.id'], name=op.f('fk_nfts_template_id_nft_templates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nfts')),
    sa.UniqueConstraint('current_location', name=op.f('uq_nfts_current_location')),
    sa.UniqueConstraint('id_on_chain', name=op.f('uq_nfts_id_on_chain')),
    sa.UniqueConstraint('origin', name=op.f('uq_nfts_origin'))
    )
    with op.batch_alter_table('nfts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfts_prefix'), ['prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfts_template_id'), ['template_id'], unique=False)

    op.create_table('blockchain_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_paymail', sa.String(length=100), nullable=True),
    sa.Column('nft_id', sa.Integer(), nullable=True),
    sa.Column('unique_nft_id', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tx_hash', sa.String(length=255), nullable=True),
    sa.Column('request_payload_json', sa.Text(), nullable=True),
    sa.Column('response_payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued','sent','confirmed','failed')", name=op.f('ck_blockchain_transactions_status_enum')),
    sa.CheckConstraint("type IN ('mint','transfer','burn')", name=op.f('ck_blockchain_transactions_type_enum')),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], name=op.f('fk_blockchain_transactions_nft_id_nfts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_paymail'], ['users.paymail'], name=op.f('fk_blockchain_transactions_user_paymail_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blockchain_transactions')),
    sa.UniqueConstraint('tx_hash', name=op.f('uq_blockchain_transactions_tx_hash'))
    )
    with op.batch_alter_table('blockchain_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_chain_nft', ['nft_id'], unique=False)
        batch_op.create_index('ix_chain_status', ['status'], unique=False)
        batch_op.create_index('ix_chain_type_status', ['type', 'status'], unique=False)
        batch_op.create_index('ix_chain_user_paymail', ['user_paymail'], unique=False)

    op.create_table('nft_coupon_bindings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nft_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('quantity_per_claim', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], name=op.f('fk_nft_coupon_bindings_nft_id_nfts')),
    sa.ForeignKeyConstraint(['template_id'], ['coupon_templates.id'], name=op.f('fk_nft_coupon_bindings_template_id_coupon_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nft_coupon_bindings'))
    )
    with op.batch_alter_table('nft_coupon_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nft_coupon_bindings_id'), ['id'], unique=False)

    op.create_table('user_nft_ownership',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nft_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.Integer(), nullable=False),
    sa.Column('unique_nft_id', sa.String(length=255), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('other_meta', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], name=op.f('fk_user_nft_ownership_nft_id_nfts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_nft_ownership_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_nft_ownership')),
    sa.UniqueConstraint('nft_id', 'serial_number', name='uq_nft_serial'),
    sa.UniqueConstraint('unique_nft_id', name=op.f('uq_user_nft_ownership_unique_nft_id')),
    sa.UniqueConstraint('user_id', 'nft_id', name='uq_user_nft')
    )
    with op.batch_alter_table('user_nft_ownership', schema=None) as batch_op:
        batch_op.create_index('ix_unique_nft_id', ['unique_nft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_nft_ownership_nft_id'), ['nft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_nft_ownership_user_id'), ['user_id'], unique=False)

    op.create_table('bingo_cells',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bingo_card_id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('target_template_id', sa.Integer(), nullable=False),
    sa.Column('nft_id', sa.Integer(), nullable=True),
    sa.Column('matched_ownership_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(state = 'locked' AND nft_id IS NULL AND matched_ownership_id IS NULL) OR (state = 'unlocked' AND nft_id IS NOT NULL AND matched_ownership_id IS NOT NULL)", name=op.f('ck_bingo_cells_locked_unlocked_consistency')),
    sa.CheckConstraint("state IN ('locked','unlocked')", name=op.f('ck_bingo_cells_state_enum')),
    sa.CheckConstraint('idx >= 0 AND idx <= 8', name=op.f('ck_bingo_cells_idx_range')),
    sa.ForeignKeyConstraint(['bingo_card_id'], ['bingo_cards.id'], name=op.f('fk_bingo_cells_bingo_card_id_bingo_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_ownership_id'], ['user_nft_ownership.id'], name=op.f('fk_bingo_cells_matched_ownership_id_user_nft_ownership'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], name=op.f('fk_bingo_cells_nft_id_nfts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_template_id'], ['nft_templates.id'], name=op.f('fk_bingo_cells_target_template_id_nft_templates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bingo_cells')),
    sa.UniqueConstraint('bingo_card_id', 'idx', name='uq_card_idx')
    )
    with op.batch_alter_table('bingo_cells', schema=None) as batch_op:
        batch_op.create_index('ix_bingo_cells_card', ['bingo_card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bingo_cells_nft_id'), ['nft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bingo_cells_target_template_id'), ['target_template_id'], unique=False)

    op.create_table('coupon_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('nft_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ownership_id', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sa.String(length=128), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redeemed', sa.Boolean(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('store_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], name=op.f('fk_coupon_instances_nft_id_nfts')),
    sa.ForeignKeyConstraint(['ownership_id'], ['user_nft_ownership.id'], name=op.f('fk_coupon_instances_ownership_id_user_nft_ownership')),
    sa.ForeignKeyConstraint(['template_id'], ['coupon_templates.id'], name=op.f('fk_coupon_instances_template_id_coupon_templates')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_coupon_instances_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupon_instances')),
    sa.UniqueConstraint('coupon_code', name=op.f('uq_coupon_instances_coupon_code'))
    )
    with op.batch_alter_table('coupon_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupon_instances_id'), ['id'], unique=False)

    op.create_table('prize_draw_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draw_type_id', sa.Integer(), nullable=False),
    sa.Column('winning_number_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nft_id', sa.Integer(), nullable=False),
    sa.Column('ownership_id', sa.Integer(), nullable=True),
    sa.Column('draw_number', sa.String(length=255), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('draw_top_digits', sa.String(length=10), nullable=True),
    sa.Column('winning_top_digits', sa.String(length=10), nullable=True),
    sa.Column('threshold_used', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['draw_type_id'], ['prize_draw_types.id'], name=op.f('fk_prize_draw_results_draw_type_id_prize_draw_types'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], name=op.f('fk_prize_draw_results_nft_id_nfts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ownership_id'], ['user_nft_ownership.id'], name=op.f('fk_prize_draw_results_ownership_id_user_nft_ownership'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_prize_draw_results_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winning_number_id'], ['prize_draw_winning_numbers.id'], name=op.f('fk_prize_draw_results_winning_number_id_prize_draw_winning_numbers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prize_draw_results')),
    sa.UniqueConstraint('nft_id', 'draw_type_id', name='uq_draw_result_unique')
    )
    with op.batch_alter_table('prize_draw_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prize_draw_results_draw_type_id'), ['draw_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prize_draw_results_nft_id'), ['nft_id'], unique=False)
        batch_op.create_index('ix_prize_draw_results_outcome', ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_prize_draw_results_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prize_draw_results_winning_number_id'), ['winning_number_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prize_draw_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prize_draw_results_winning_number_id'))
        batch_op.drop_index(batch_op.f('ix_prize_draw_results_user_id'))
        batch_op.drop_index('ix_prize_draw_results_outcome')
        batch_op.drop_index(batch_op.f('ix_prize_draw_results_nft_id'))
        batch_op.drop_index(batch_op.f('ix_prize_draw_results_draw_type_id'))

    op.drop_table('prize_draw_results')
    with op.batch_alter_table('coupon_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupon_instances_id'))

    op.drop_table('coupon_instances')
    with op.batch_alter_table('bingo_cells', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bingo_cells_target_template_id'))
        batch_op.drop_index(batch_op.f('ix_bingo_cells_nft_id'))
        batch_op.drop_index('ix_bingo_cells_card')

    op.drop_table('bingo_cells')
    with op.batch_alter_table('user_nft_ownership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_nft_ownership_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_nft_ownership_nft_id'))
        batch_op.drop_index('ix_unique_nft_id')

    op.drop_table('user_nft_ownership')
    with op.batch_alter_table('nft_coupon_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nft_coupon_bindings_id'))

    op.drop_table('nft_coupon_bindings')
    with op.batch_alter_table('blockchain_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_chain_user_paymail')
        batch_op.drop_index('ix_chain_type_status')
        batch_op.drop_index('ix_chain_status')
        batch_op.drop_index('ix_chain_nft')

    op.drop_table('blockchain_transactions')
    with op.batch_alter_table('nfts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfts_template_id'))
        batch_op.drop_index(batch_op.f('ix_nfts_prefix'))

    op.drop_table('nfts')
    with op.batch_alter_table('prize_draw_winning_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prize_draw_winning_numbers_draw_type_id'))

    op.drop_table('prize_draw_winning_numbers')
    with op.batch_alter_table('nft_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nft_templates_prefix'))

    op.drop_table('nft_templates')
    with op.batch_alter_table('bingo_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bingo_cards_user_id'))

    op.drop_table('bingo_cards')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('prize_draw_types')
    with op.batch_alter_table('nft_conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nft_conditions_internal_name'))

    op.drop_table('nft_conditions')
    with op.batch_alter_table('coupon_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupon_templates_id'))

    op.drop_table('coupon_templates')
    op.drop_table('admins')
    # ### end Alembic commands ###
