"""sync transit api schema post 20260203

Revision ID: fb03c2018550
Revises: 664ae0905bb7
Create Date: 2026-02-27 16:01:40.005099

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb03c2018550'
down_revision: Union[str, Sequence[str], None] = '664ae0905bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_bingo_duplicates', sa.Boolean(), server_default=sa.text('(true)'), nullable=False))
        batch_op.add_column(sa.Column('bingo_group_id', sa.Integer(), nullable=True))
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(true)'),
               existing_nullable=False)

    with op.batch_alter_table('user_nft_ownership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nft_id_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('user_claim_hash', sa.String(length=64), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_test_user', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))

    op.execute(
        sa.text(
            "UPDATE nfts SET bingo_group_id = 1 WHERE status = 'active' AND nft_type IN ('shop', 'match')"
        )
    )
    op.execute(sa.text("UPDATE nfts SET bingo_group_id = 2 WHERE id IN (109, 110, 111, 113, 115)"))
    op.execute(sa.text("UPDATE users SET is_test_user = true WHERE email LIKE 'nictbw2026%'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_test_user')

    with op.batch_alter_table('user_nft_ownership', schema=None) as batch_op:
        batch_op.drop_column('user_claim_hash')
        batch_op.drop_column('nft_id_hash')

    with op.batch_alter_table('nfts', schema=None) as batch_op:
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(false)'),
               existing_nullable=False)
        batch_op.drop_column('bingo_group_id')
        batch_op.drop_column('allow_bingo_duplicates')

    # ### end Alembic commands ###
